name: devops-observability

services:

  prometheus:
    image: prom/prometheus:v3.12.0

    restart: unless-stopped

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.enable-lifecycle"

    ports:
      - "192.168.100.88:9090:9090"

    volumes:
      - "../../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z"
      - "prometheus-data:/prometheus"

    networks:
      - observability-network

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:v0.28.0

    restart: unless-stopped

    command:
      - "--config.file=/config/blackbox.yml"

    ports:
      - "127.0.0.1:9115:9115"

    volumes:
      - "../../blackbox/blackbox.yml:/config/blackbox.yml:ro,Z"

    networks:
      - observability-network

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.11.1

    restart: unless-stopped

    network_mode: host
    pid: host

    security_opt:
      - "label=disable"

    command:
      - "--path.rootfs=/host"
      - "--web.listen-address=192.168.100.88:9100"

    volumes:
      - "/:/host:ro,rslave"

  grafana:
    image: grafana/grafana:13.1.0

    restart: unless-stopped

    depends_on:
      - prometheus

    ports:
      - "192.168.100.88:3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
      GF_SECURITY_SECRET_KEY__FILE: /run/secrets/grafana_secret_key

      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "false"

      GF_SECURITY_DISABLE_GRAVATAR: "true"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"

      GF_SERVER_ENABLE_GZIP: "true"

    secrets:
      - grafana_admin_password
      - grafana_secret_key

    volumes:
      - "grafana-data:/var/lib/grafana"
      - "../../grafana/provisioning:/etc/grafana/provisioning:ro,Z"
      - "../../grafana/dashboards:/etc/grafana/dashboards:ro,Z"

    networks:
      - observability-network

volumes:

  prometheus-data:
    name: devops-observability-prometheus-data

  grafana-data:
    name: devops-observability-grafana-data

networks:

  observability-network:
    name: devops-observability-network
    driver: bridge

secrets:

  grafana_admin_password:
    file: ../../secrets/grafana_admin_password.txt

  grafana_secret_key:
    file: ../../secrets/grafana_secret_key.txt
